variables:
  CI: true
trigger:
  - master
jobs:
  - job:
    displayName: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: make -j"$(cat /proc/cpuinfo | grep -e '^processor' | wc -l)"
        displayName: Build
  - job:
    displayName: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - script: make
        displayName: Build
  - job:
    displayName: macOS
    pool:
      vmImage: 'macOS-latest'
    variables:
      RUSTUP_HOME: $(Pipeline.Workspace)/.rustup
      CARGO_HOME: $(Pipeline.Workspace)/.cargo
    steps:
      - checkout: self
        fetchDepth: 1
      - script: |
          curl -sSf https://sh.rustup.rs | bash -s -- -v -y --no-modify-path
          echo "##vso[task.prependpath]$(CARGO_HOME)/bin"
        displayName: Setup Rust
      - script: make -j"$(sysctl hw.logicalcpu | cut -d' ' -f2)"
        displayName: Build
