[package]
name = "montecarlo-pi"
version = "0.1.0"
authors = ["Satoru Sukawa <sukawasatoru.github@outlook.jp>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.1"
dotenv = "0.13.0"
failure = "0.1.5"
futures = "0.1.25"
num_cpus = "1.10.0"
rand = "0.7.0"
structopt = "0.2.15"
tokio = "0.1.17"
